<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterDati2Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['dati2' => '0102', 'nama' => 'BEKASI, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0103', 'nama' => 'PURWAKARTA, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0106', 'nama' => 'KARAWANG, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0108', 'nama' => 'BOGOR, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0109', 'nama' => 'SUKABUPATENUMI, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0110', 'nama' => 'CIANJUR, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0111', 'nama' => 'BANDUNG, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0112', 'nama' => 'SUMEDANG, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0113', 'nama' => 'TASIKMALAYA, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0114', 'nama' => 'GARUT, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0115', 'nama' => 'CIAMIS, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0116', 'nama' => 'CIREBON, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0117', 'nama' => 'KUNINGAN, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0118', 'nama' => 'INDRAMAYU, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0119', 'nama' => 'MAJALENGKA, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0121', 'nama' => 'SUBANG, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0122', 'nama' => 'BANDUNG BARAT, KABUPATEN', 'province_id' => '32'],
            ['dati2' => '0123', 'nama' => 'PANGANDARAN, KABUPATENUPATEN', 'province_id' => '32'],
            ['dati2' => '0180', 'nama' => 'BANJAR, KOTA', 'province_id' => '32'],
            ['dati2' => '0188', 'nama' => 'PROV JAWA BARAT, KABUPATEN/KOTA LAINNYA', 'province_id' => '32'],
            ['dati2' => '0191', 'nama' => 'BANDUNG, KOTA', 'province_id' => '32'],
            ['dati2' => '0192', 'nama' => 'BOGOR, KOTA', 'province_id' => '32'],
            ['dati2' => '0193', 'nama' => 'SUKABUPATENUMI, KOTA', 'province_id' => '32'],
            ['dati2' => '0194', 'nama' => 'CIREBON, KOTA', 'province_id' => '32'],
            ['dati2' => '0195', 'nama' => 'TASIKMALAYA, KOTA', 'province_id' => '32'],
            ['dati2' => '0196', 'nama' => 'CIMAHI, KOTA', 'province_id' => '32'],
            ['dati2' => '0197', 'nama' => 'DEPOK, KOTA', 'province_id' => '32'],
            ['dati2' => '0198', 'nama' => 'BEKASI, KOTA', 'province_id' => '32'],
            ['dati2' => '0201', 'nama' => 'LEBAK, KABUPATEN', 'province_id' => '36'],
            ['dati2' => '0202', 'nama' => 'PANDEGLANG, KABUPATEN', 'province_id' => '36'],
            ['dati2' => '0203', 'nama' => 'SERANG, KABUPATEN', 'province_id' => '36'],
            ['dati2' => '0204', 'nama' => 'TANGERANG, KABUPATEN', 'province_id' => '36'],
            ['dati2' => '0288', 'nama' => 'PROV BANTEN, KABUPATEN/KOTA LAINNYA', 'province_id' => '36'],
            ['dati2' => '0291', 'nama' => 'CILEGON, KOTA', 'province_id' => '36'],
            ['dati2' => '0292', 'nama' => 'TANGERANG, KOTA', 'province_id' => '36'],
            ['dati2' => '0293', 'nama' => 'SERANG KOTA', 'province_id' => '36'],
            ['dati2' => '0294', 'nama' => 'KOTA TANGERANG SELATAN', 'province_id' => '36'],
            ['dati2' => '0300', 'nama' => 'DKI JAKARTA', 'province_id' => '31'],
            ['dati2' => '0391', 'nama' => 'JAKARTA PUSAT, WIL KOTA', 'province_id' => '31'],
            ['dati2' => '0392', 'nama' => 'JAKARTA UTARA, WIL KOTA', 'province_id' => '31'],
            ['dati2' => '0393', 'nama' => 'JAKARTA BARAT, WIL KOTA', 'province_id' => '31'],
            ['dati2' => '0394', 'nama' => 'JAKARTA SELATAN, WIL KOTA', 'province_id' => '31'],
            ['dati2' => '0395', 'nama' => 'JAKARTA TIMUR, WIL KOTA', 'province_id' => '31'],
            ['dati2' => '0396', 'nama' => 'KEPULAUAN SERIBU, WILAYAH', 'province_id' => '31'],
            ['dati2' => '0500', 'nama' => 'DI YOGYAKARTA', 'province_id' => '34'],
            ['dati2' => '0501', 'nama' => 'BANTUL, KABUPATEN', 'province_id' => '34'],
            ['dati2' => '0502', 'nama' => 'SLEMAN, KABUPATEN', 'province_id' => '34'],
            ['dati2' => '0503', 'nama' => 'GUNUNG KIDUL, KABUPATEN', 'province_id' => '34'],
            ['dati2' => '0504', 'nama' => 'KULON PROGO, KABUPATEN', 'province_id' => '34'],
            ['dati2' => '0588', 'nama' => 'DI YOGYAKARTA, KABUPATEN/KOTA LAINNYA', 'province_id' => '34'],
            ['dati2' => '0591', 'nama' => 'YOGYAKARTA, KOTA', 'province_id' => '34'],
            ['dati2' => '0901', 'nama' => 'SEMARANG, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0902', 'nama' => 'KENDAL, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0903', 'nama' => 'DEMAK, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0904', 'nama' => 'GROBOGAN, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0905', 'nama' => 'PEKALONGAN, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0906', 'nama' => 'TEGAL, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0907', 'nama' => 'BREBES, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0908', 'nama' => 'PATI, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0909', 'nama' => 'KUDUS, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0910', 'nama' => 'PEMALANG, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0911', 'nama' => 'JEPARA, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0912', 'nama' => 'REMBANG, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0913', 'nama' => 'BLORA, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0914', 'nama' => 'BANYUMAS, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0915', 'nama' => 'CILACAP, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0916', 'nama' => 'PURBALINGGA, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0917', 'nama' => 'BANJARNEGARA, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0918', 'nama' => 'MAGELANG, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0919', 'nama' => 'TEMANGGUNG, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0920', 'nama' => 'WONOSOBO, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0921', 'nama' => 'PURWOREJO, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0922', 'nama' => 'KEBUMEN, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0923', 'nama' => 'KLATEN, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0924', 'nama' => 'BOYOLALI, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0925', 'nama' => 'SRAGEN, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0926', 'nama' => 'SUKOHARJO, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0927', 'nama' => 'KARANGANYAR, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0928', 'nama' => 'WONOGIRI, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0929', 'nama' => 'BATANG, KABUPATEN', 'province_id' => '33'],
            ['dati2' => '0988', 'nama' => 'PROV JAWA TENGAH, KABUPATEN/KOTA LAINNYA', 'province_id' => '33'],
            ['dati2' => '0991', 'nama' => 'SEMARANG, KOTA', 'province_id' => '33'],
            ['dati2' => '0992', 'nama' => 'SALATIGA, KOTA', 'province_id' => '33'],
            ['dati2' => '0993', 'nama' => 'PEKALONGAN, KOTA', 'province_id' => '33'],
            ['dati2' => '0994', 'nama' => 'TEGAL, KOTA', 'province_id' => '33'],
            ['dati2' => '0995', 'nama' => 'MAGELANG, KOTA', 'province_id' => '33'],
            ['dati2' => '0996', 'nama' => 'SURAKARTA, KOTA', 'province_id' => '33'],
            ['dati2' => '1201', 'nama' => 'GRESIK, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1202', 'nama' => 'SIDOARJO, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1203', 'nama' => 'MOJOKERTO, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1204', 'nama' => 'JOMBANG, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1205', 'nama' => 'SAMPANG, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1206', 'nama' => 'PAMEKASAN, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1207', 'nama' => 'SUMENEP, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1208', 'nama' => 'BANGKALAN, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1209', 'nama' => 'BONDOWOSO, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1211', 'nama' => 'BANYUWANGI, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1212', 'nama' => 'JEMBER, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1213', 'nama' => 'MALANG, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1214', 'nama' => 'PASURUAN, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1215', 'nama' => 'PROBOLINGGO, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1216', 'nama' => 'LUMAJANG, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1217', 'nama' => 'KEDIRI, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1218', 'nama' => 'NGANJUK, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1219', 'nama' => 'TULUNGAGUNG, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1220', 'nama' => 'TRENGGALEK, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1221', 'nama' => 'BLITAR, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1222', 'nama' => 'MADIUN, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1223', 'nama' => 'NGAWI, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1224', 'nama' => 'MAGETAN, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1225', 'nama' => 'PONOROGO, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1226', 'nama' => 'PACITAN, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1227', 'nama' => 'BOJONEGORO, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1228', 'nama' => 'TUBAN, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1229', 'nama' => 'LAMONGAN, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1230', 'nama' => 'SITUBONDO, KABUPATEN', 'province_id' => '35'],
            ['dati2' => '1271', 'nama' => 'BATU, KOTA', 'province_id' => '35'],
            ['dati2' => '1288', 'nama' => 'PROV JAWA TIMUR, KABUPATEN/KOTA LAINNYA', 'province_id' => '35'],
            ['dati2' => '1291', 'nama' => 'SURABAYA, KOTA', 'province_id' => '35'],
            ['dati2' => '1292', 'nama' => 'MOJOKERTO, KOTA', 'province_id' => '35'],
            ['dati2' => '1293', 'nama' => 'MALANG, KOTA', 'province_id' => '35'],
            ['dati2' => '1294', 'nama' => 'PASURUAN, KOTA', 'province_id' => '35'],
            ['dati2' => '1295', 'nama' => 'PROBOLINGGO, KOTA', 'province_id' => '35'],
            ['dati2' => '1296', 'nama' => 'BLITAR, KOTA', 'province_id' => '35'],
            ['dati2' => '1297', 'nama' => 'KEDIRI, KOTA', 'province_id' => '35'],
            ['dati2' => '1298', 'nama' => 'MADIUN, KOTA', 'province_id' => '35'],
            ['dati2' => '2301', 'nama' => 'BENGKULU SELATAN, KABUPATEN', 'province_id' => '17'],
            ['dati2' => '2302', 'nama' => 'BENGKULU UTARA, KABUPATEN', 'province_id' => '17'],
            ['dati2' => '2303', 'nama' => 'REJANG LEBONG, KABUPATEN', 'province_id' => '17'],
            ['dati2' => '2304', 'nama' => 'LEBONG, KABUPATEN', 'province_id' => '17'],
            ['dati2' => '2305', 'nama' => 'KEPAHIANG, KABUPATEN', 'province_id' => '17'],
            ['dati2' => '2306', 'nama' => 'MUKOMUKO, KABUPATEN', 'province_id' => '17'],
            ['dati2' => '2307', 'nama' => 'SELUMA, KABUPATEN', 'province_id' => '17'],
            ['dati2' => '2308', 'nama' => 'KAUR, KABUPATEN', 'province_id' => '17'],
            ['dati2' => '2309', 'nama' => 'KABUPATEN BENGKULU TENGAH', 'province_id' => '17'],
            ['dati2' => '2388', 'nama' => 'PROV BENGKULU, KABUPATEN/KOTA LAINNYA', 'province_id' => '17'],
            ['dati2' => '2391', 'nama' => 'BENGKULU, KOTA', 'province_id' => '17'],
            ['dati2' => '3101', 'nama' => 'BATANGHARI, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3104', 'nama' => 'SAROLANGUN, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3105', 'nama' => 'KERINCI, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3106', 'nama' => 'MUARO JAMBI, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3107', 'nama' => 'TANJUNG JABUNG BARAT, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3108', 'nama' => 'TANJUNG JABUNG TIMUR, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3109', 'nama' => 'TEBO, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3111', 'nama' => 'MERANGIN, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3112', 'nama' => 'BUNGO, KABUPATEN', 'province_id' => '15'],
            ['dati2' => '3188', 'nama' => 'PROV JAMBI, KABUPATEN/KOTA LAINNYA', 'province_id' => '15'],
            ['dati2' => '3191', 'nama' => 'JAMBI, KOTA', 'province_id' => '15'],
            ['dati2' => '3192', 'nama' => 'KOTA SUNGAI PENUH', 'province_id' => '15'],
            ['dati2' => '3201', 'nama' => 'ACEH BESAR, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3202', 'nama' => 'PIDIE, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3203', 'nama' => 'ACEH UTARA, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3204', 'nama' => 'ACEH TIMUR, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3205', 'nama' => 'ACEH SELATAN, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3206', 'nama' => 'ACEH BARAT, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3207', 'nama' => 'ACEH TENGAH, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3208', 'nama' => 'ACEH TENGGARA, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3209', 'nama' => 'ACEH SINGKIL, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3210', 'nama' => 'ACEH JEUMPA/BIREUEN, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3211', 'nama' => 'ACEH TAMIANG, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3212', 'nama' => 'GAYO LUWES, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3213', 'nama' => 'ACEH BARAT DAYA, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3214', 'nama' => 'ACEH JAYA, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3215', 'nama' => 'NAGAN RAYA, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3216', 'nama' => 'KABUPATEN SIMEULEU', 'province_id' => '11'],
            ['dati2' => '3217', 'nama' => 'KABUPATEN BENER MERIAH', 'province_id' => '11'],
            ['dati2' => '3218', 'nama' => 'PIDE JAYA, KABUPATEN', 'province_id' => '11'],
            ['dati2' => '3219', 'nama' => 'SUBULUSSALAM', 'province_id' => '11'],
            ['dati2' => '3288', 'nama' => 'PROV NAD, KABUPATEN/KOTA LAINNYA', 'province_id' => '11'],
            ['dati2' => '3291', 'nama' => 'BANDA ACEH, KOTA', 'province_id' => '11'],
            ['dati2' => '3292', 'nama' => 'SABANG, KOTA', 'province_id' => '11'],
            ['dati2' => '3293', 'nama' => 'LHOKSEUMAWE, KOTA', 'province_id' => '11'],
            ['dati2' => '3294', 'nama' => 'LANGSA, KOTA', 'province_id' => '11'],
            ['dati2' => '3301', 'nama' => 'DELI SERDANG, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3302', 'nama' => 'LANGKAT, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3303', 'nama' => 'KARO, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3304', 'nama' => 'SIMALUNGUN, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3305', 'nama' => 'LABUHAN BATU, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3306', 'nama' => 'ASAHAN, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3307', 'nama' => 'DAIRI, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3308', 'nama' => 'TAPANULI UTARA, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3309', 'nama' => 'TAPANULI TENGAH, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3310', 'nama' => 'TAPANULI SELATAN, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3311', 'nama' => 'NIAS, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3313', 'nama' => 'TOBA SAMOSIR, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3314', 'nama' => 'MANDAILING NATAL, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3315', 'nama' => 'NIAS SELATAN, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3316', 'nama' => 'HUMBANG HASUNDUTAN, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3317', 'nama' => 'PAKPAK BARAT, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3318', 'nama' => 'SAMOSIR, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3319', 'nama' => 'SERDANG BEDAGAI, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3320', 'nama' => 'ANGKOLA SIPIROK, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3321', 'nama' => 'BATU BARA, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3322', 'nama' => 'PADANG LAWAS, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3323', 'nama' => 'PADANG LAWAS UTARA, KABUPATEN', 'province_id' => '12'],
            ['dati2' => '3324', 'nama' => 'KABUPATEN LABUANBATU SELATAN', 'province_id' => '12'],
            ['dati2' => '3325', 'nama' => 'KABUPATEN LABUANBATU UTARA', 'province_id' => '12'],
            ['dati2' => '3326', 'nama' => 'KABUPATEN NIAS BARAT', 'province_id' => '12'],
            ['dati2' => '3327', 'nama' => 'KABUPATEN NIAS UTARA', 'province_id' => '12'],
            ['dati2' => '3388', 'nama' => 'PROV SUMATERA UTARA, KABUPATEN/KOTA LAINNYA', 'province_id' => '12'],
            ['dati2' => '3391', 'nama' => 'TEBING TINGGI, KOTA', 'province_id' => '12'],
            ['dati2' => '3392', 'nama' => 'BINJAI, KOTA', 'province_id' => '12'],
            ['dati2' => '3393', 'nama' => 'PEMATANG SIANTAR, KOTA', 'province_id' => '12'],
            ['dati2' => '3394', 'nama' => 'TANJUNG BALAI, KOTA', 'province_id' => '12'],
            ['dati2' => '3395', 'nama' => 'SIBOLGA, KOTA', 'province_id' => '12'],
            ['dati2' => '3396', 'nama' => 'MEDAN, KOTA', 'province_id' => '12'],
            ['dati2' => '3397', 'nama' => 'KOTA GUNUNG SITOLI', 'province_id' => '12'],
            ['dati2' => '3399', 'nama' => 'PADANG SIDEMPUAN, KOTA', 'province_id' => '12'],
            ['dati2' => '3401', 'nama' => 'AGAM, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3402', 'nama' => 'PASAMAN, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3403', 'nama' => 'LIMAPULUH KOTO, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3404', 'nama' => 'SOLOK SELATAN, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3405', 'nama' => 'PADANG PARIAMAN, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3406', 'nama' => 'PESISIR SELATAN, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3407', 'nama' => 'TANAH DATAR, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3408', 'nama' => 'KABUPATEN SIJUNJUNG', 'province_id' => '13'],
            ['dati2' => '3409', 'nama' => 'KEPULAUAN MENTAWAI, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3410', 'nama' => 'PASAMAN BARAT, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3411', 'nama' => 'DHARMASRAYA, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3412', 'nama' => 'SOLOK, KABUPATEN', 'province_id' => '13'],
            ['dati2' => '3488', 'nama' => 'PROV SUMATERA BARAT, KABUPATEN/KOTA LAINNYA', 'province_id' => '13'],
            ['dati2' => '3491', 'nama' => 'BUKITTINGGI, KOTA', 'province_id' => '13'],
            ['dati2' => '3492', 'nama' => 'PADANG, KOTA', 'province_id' => '13'],
            ['dati2' => '3493', 'nama' => 'SAWAHLUNTO, KOTA', 'province_id' => '13'],
            ['dati2' => '3494', 'nama' => 'PADANG PANJANG, KOTA', 'province_id' => '13'],
            ['dati2' => '3495', 'nama' => 'SOLOK, KOTA', 'province_id' => '13'],
            ['dati2' => '3496', 'nama' => 'PAYAKUMBUH, KOTA', 'province_id' => '13'],
            ['dati2' => '3497', 'nama' => 'PARIAMAN, KOTA', 'province_id' => '13'],
            ['dati2' => '3501', 'nama' => 'KAMPAR, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3502', 'nama' => 'BENGKALIS, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3504', 'nama' => 'INDRAGIRI HULU, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3505', 'nama' => 'INDRAGIRI HILIR, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3508', 'nama' => 'ROKAN HULU, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3509', 'nama' => 'ROKAN HILIR, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3510', 'nama' => 'PELALAWAN, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3511', 'nama' => 'SIAK, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3512', 'nama' => 'KUANTAN SINGINGI, KABUPATEN', 'province_id' => '14'],
            ['dati2' => '3513', 'nama' => 'KABUPATEN KEPULAUAN MERANTI', 'province_id' => '14'],
            ['dati2' => '3588', 'nama' => 'PROV RIAU, KABUPATEN/KOTA LAINNYA', 'province_id' => '14'],
            ['dati2' => '3591', 'nama' => 'PEKANBARU, KOTA', 'province_id' => '14'],
            ['dati2' => '3592', 'nama' => 'DUMAI, KOTA', 'province_id' => '14'],
            ['dati2' => '3606', 'nama' => 'MUSI BANYUASIN, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3607', 'nama' => 'OGAN KOMERING ULU, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3608', 'nama' => 'LEMATANG ILIR OGAN TENGAH (MUARA ENIM), KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3609', 'nama' => 'LAHAT, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3610', 'nama' => 'MUSI RAWAS, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3611', 'nama' => 'OGAN KOMERING ILIR, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3613', 'nama' => 'BANYUASIN, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3614', 'nama' => 'OGAN KOMERING ULU SELATAN, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3615', 'nama' => 'OGAN KOMERING ULU TIMUR, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3616', 'nama' => 'OGAN ILIR, KABUPATEN', 'province_id' => '16'],
            ['dati2' => '3617', 'nama' => 'EMPAT LAWANG', 'province_id' => '16'],
            ['dati2' => '3618', 'nama' => 'MUSI RAWAS UTARA, KABUPATENUPATEN', 'province_id' => '16'],
            ['dati2' => '3619', 'nama' => 'PANUKAL ABAB LEMATANG ILIR KABUPATENUPATEN', 'province_id' => '16'],
            ['dati2' => '3688', 'nama' => 'PROV SUMATERA SELATAN, KABUPATEN/KOTA LAINNYA', 'province_id' => '16'],
            ['dati2' => '3691', 'nama' => 'PALEMBANG, KOTA', 'province_id' => '16'],
            ['dati2' => '3693', 'nama' => 'LUBUKLINGGAU, KOTA', 'province_id' => '16'],
            ['dati2' => '3694', 'nama' => 'PRABUMULIH, KOTA', 'province_id' => '16'],
            ['dati2' => '3697', 'nama' => 'PAGAR ALAM, KOTA', 'province_id' => '16'],
            ['dati2' => '3701', 'nama' => 'BANGKA, KABUPATEN', 'province_id' => '19'],
            ['dati2' => '3702', 'nama' => 'BELITUNG, KABUPATEN', 'province_id' => '19'],
            ['dati2' => '3703', 'nama' => 'BANGKA BARAT, KABUPATEN', 'province_id' => '19'],
            ['dati2' => '3704', 'nama' => 'BANGKA SELATAN, KABUPATEN', 'province_id' => '19'],
            ['dati2' => '3705', 'nama' => 'BANGKA TENGAH, KABUPATEN', 'province_id' => '19'],
            ['dati2' => '3706', 'nama' => 'BELITUNG TIMUR, KABUPATEN', 'province_id' => '19'],
            ['dati2' => '3707', 'nama' => 'KABUPATEN BANGKA BELITUNG', 'province_id' => '19'],
            ['dati2' => '3788', 'nama' => 'PROV BABEL, KABUPATEN/KOTA LAINNYA', 'province_id' => '19'],
            ['dati2' => '3791', 'nama' => 'PANGKAL PINANG, KOTA', 'province_id' => '19'],
            ['dati2' => '3801', 'nama' => 'KARIMUN, KABUPATEN', 'province_id' => '21'],
            ['dati2' => '3802', 'nama' => 'LINGGA, KABUPATEN', 'province_id' => '21'],
            ['dati2' => '3803', 'nama' => 'NATUNA, KABUPATEN', 'province_id' => '21'],
            ['dati2' => '3804', 'nama' => 'BINTAN, KABUPATEN (D/H KABUPATEN KEPULAUAN RIAU', 'province_id' => '21'],
            ['dati2' => '3805', 'nama' => 'KABUPATEN ANAMBAS', 'province_id' => '21'],
            ['dati2' => '3888', 'nama' => 'PROV KEPULAUAN RIAU, KABUPATEN/KOTA LAINNYA', 'province_id' => '21'],
            ['dati2' => '3891', 'nama' => 'TANJUNGPINANG, KOTA', 'province_id' => '21'],
            ['dati2' => '3892', 'nama' => 'BATAM, KOTA', 'province_id' => '21'],
            ['dati2' => '3901', 'nama' => 'LAMPUNG SELATAN, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3902', 'nama' => 'LAMPUNG TENGAH, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3903', 'nama' => 'LAMPUNG UTARA, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3904', 'nama' => 'LAMPUNG BARAT, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3905', 'nama' => 'TULANG BAWANG, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3906', 'nama' => 'TANGGAMUS, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3907', 'nama' => 'LAMPUNG TIMUR, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3908', 'nama' => 'WAY KANAN, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3909', 'nama' => 'PESAWARAN, KABUPATEN', 'province_id' => '18'],
            ['dati2' => '3910', 'nama' => 'KABUPATEN PRINGSEWU', 'province_id' => '18'],
            ['dati2' => '3911', 'nama' => 'KABUPATEN TULANG BAWANG BARAT', 'province_id' => '18'],
            ['dati2' => '3912', 'nama' => 'KABUPATEN MESUJI', 'province_id' => '18'],
            ['dati2' => '3913', 'nama' => 'PESISIR BARAT, KABUPATENUPATEN', 'province_id' => '18'],
            ['dati2' => '3988', 'nama' => 'PROV LAMPUNG, KABUPATEN/KOTA LAINNYA', 'province_id' => '18'],
            ['dati2' => '3991', 'nama' => 'BANDAR LAMPUNG, KOTA', 'province_id' => '18'],
            ['dati2' => '3992', 'nama' => 'METRO, KOTA', 'province_id' => '18'],
            ['dati2' => '5101', 'nama' => 'BANJAR, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5102', 'nama' => 'TANAH LAUT, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5103', 'nama' => 'TAPIN, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5104', 'nama' => 'HULU SUNGAI SELATAN, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5105', 'nama' => 'HULU SUNGAI TENGAH, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5106', 'nama' => 'HULU SUNGAI UTARA, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5107', 'nama' => 'BARITO KUALA, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5108', 'nama' => 'KOTA BARU, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5109', 'nama' => 'TABALONG, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5110', 'nama' => 'TANAH BUMBU, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5111', 'nama' => 'BALANGAN, KABUPATEN', 'province_id' => '63'],
            ['dati2' => '5188', 'nama' => 'PROV KAL SEL, KABUPATEN/KOTA LAINNYA', 'province_id' => '63'],
            ['dati2' => '5191', 'nama' => 'BANJARMASIN, KOTA', 'province_id' => '63'],
            ['dati2' => '5192', 'nama' => 'BANJARBARU, KOTA', 'province_id' => '63'],
            ['dati2' => '5301', 'nama' => 'PONTIANAK, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5302', 'nama' => 'SAMBAS, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5303', 'nama' => 'KETAPANG, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5304', 'nama' => 'SANGGAU, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5305', 'nama' => 'SINTANG, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5306', 'nama' => 'KAPUAS HULU, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5307', 'nama' => 'BENGKAYANG, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5308', 'nama' => 'LANDAK, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5309', 'nama' => 'SEKADAU, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5310', 'nama' => 'MELAWI, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5311', 'nama' => 'KAYONG UTARA, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5312', 'nama' => 'KUBU RAYA, KABUPATEN', 'province_id' => '61'],
            ['dati2' => '5388', 'nama' => 'PROV KAL BAR, KABUPATEN/KOTA LAINNYA', 'province_id' => '61'],
            ['dati2' => '5391', 'nama' => 'PONTIANAK, KOTA', 'province_id' => '61'],
            ['dati2' => '5392', 'nama' => 'SINGKAWANG, KOTA', 'province_id' => '61'],
            ['dati2' => '5401', 'nama' => 'KUTAI KARTANEGARA, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5402', 'nama' => 'BERAU, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5403', 'nama' => 'PASIR, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5404', 'nama' => 'BULUNGAN, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5405', 'nama' => 'KUTAI BARAT, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5406', 'nama' => 'KUTAI TIMUR, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5409', 'nama' => 'NUNUKAN, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5410', 'nama' => 'MALINAU, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5411', 'nama' => 'PENAJAM PASER UTARA, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5412', 'nama' => 'TANA TIDUNG, KABUPATEN', 'province_id' => '64'],
            ['dati2' => '5413', 'nama' => 'MAHAKAM ULU, KABUPATENUPATEN', 'province_id' => '64'],
            ['dati2' => '5488', 'nama' => 'PROV KAL TIM, KABUPATEN/KOTA LAINNYA', 'province_id' => '64'],
            ['dati2' => '5491', 'nama' => 'SAMARINDA, KOTA', 'province_id' => '64'],
            ['dati2' => '5492', 'nama' => 'BALIKPAPAN, KOTA', 'province_id' => '64'],
            ['dati2' => '5493', 'nama' => 'TARAKAN, KOTA', 'province_id' => '64'],
            ['dati2' => '5494', 'nama' => 'BONTANG, KOTA', 'province_id' => '64'],
            ['dati2' => '5801', 'nama' => 'KAPUAS, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5802', 'nama' => 'KOTAWARINGIN BARAT, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5803', 'nama' => 'KOTAWARINGIN TIMUR, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5804', 'nama' => 'MURUNG RAYA, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5805', 'nama' => 'BARITO TIMUR, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5806', 'nama' => 'BARITO SELATAN, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5807', 'nama' => 'GUNUNG MAS, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5808', 'nama' => 'BARITO UTARA, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5809', 'nama' => 'PULANG PISAU, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5810', 'nama' => 'SERUYAN, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5811', 'nama' => 'KATINGAN, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5812', 'nama' => 'SUKAMARA, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5813', 'nama' => 'LAMANDAU, KABUPATEN', 'province_id' => '62'],
            ['dati2' => '5888', 'nama' => 'PROV KAL TENG, KABUPATEN/KOTA LAINNYA', 'province_id' => '62'],
            ['dati2' => '5892', 'nama' => 'PALANGKARAYA, KOTA', 'province_id' => '62'],
            ['dati2' => '6001', 'nama' => 'DONGGALA, KABUPATEN', 'province_id' => '72'],
            ['dati2' => '6002', 'nama' => 'POSO, KABUPATEN', 'province_id' => '72'],
            ['dati2' => '6003', 'nama' => 'PARIMO/BANGGAI, KABUPATEN', 'province_id' => '72'],
            ['dati2' => '6004', 'nama' => 'TOLI TOLI, KABUPATEN', 'province_id' => '72'],
            ['dati2' => '6005', 'nama' => 'KABUPATENBANGGAI KEPULAUAN', 'province_id' => '72'],
            ['dati2' => '6006', 'nama' => 'MOROWALI, KABUPATEN', 'province_id' => '72'],
            ['dati2' => '6007', 'nama' => 'BUOL, KABUPATEN', 'province_id' => '72'],
            ['dati2' => '6008', 'nama' => 'TOJO UNA UNA, KABUPATEN', 'province_id' => '72'],
            ['dati2' => '6009', 'nama' => 'PARIGI MOUTONG, KABUPATEN', 'province_id' => '72'],
            ['dati2' => '6010', 'nama' => 'KABUPATEN SIGI', 'province_id' => '72'],
            ['dati2' => '6011', 'nama' => 'BANGGAI LAUT, KABUPATENUPATEN', 'province_id' => '72'],
            ['dati2' => '6012', 'nama' => 'MOROWALI UTARA, KABUPATENUPATEN', 'province_id' => '72'],
            ['dati2' => '6088', 'nama' => 'PROV SULAWESI TENGAH, KABUPATEN/KOTA LAINNYA', 'province_id' => '72'],
            ['dati2' => '6091', 'nama' => 'PALU, KOTA', 'province_id' => '72'],
            ['dati2' => '6101', 'nama' => 'PINRANG, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6102', 'nama' => 'GOWA, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6103', 'nama' => 'WAJO, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6105', 'nama' => 'BONE, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6106', 'nama' => 'TANA TORAJA, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6107', 'nama' => 'MAROS, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6109', 'nama' => 'LUWU, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6110', 'nama' => 'SINJAI, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6111', 'nama' => 'BULUKUMBA, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6112', 'nama' => 'BANTAENG, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6113', 'nama' => 'JENEPONTO, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6114', 'nama' => 'SELAYAR, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6115', 'nama' => 'TAKALAR, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6116', 'nama' => 'BARRU, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6117', 'nama' => 'SIDENRENG RAPPANG, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6118', 'nama' => 'PANGKAJENE KEPULAUAN, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6119', 'nama' => 'KABUPATEN SOPPENG (D/H WATANSOPPENG)', 'province_id' => '73'],
            ['dati2' => '6121', 'nama' => 'ENREKANG, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6122', 'nama' => 'KABUPATEN LUWU TIMUR (D/H LUWU SELATAN)', 'province_id' => '73'],
            ['dati2' => '6124', 'nama' => 'LUWU UTARA, KABUPATEN', 'province_id' => '73'],
            ['dati2' => '6125', 'nama' => 'KABUPATEN TORAJA UTARA', 'province_id' => '73'],
            ['dati2' => '6188', 'nama' => 'PROV SULAWESI SELATAN, KABUPATEN/KOTA LAINNYA', 'province_id' => '73'],
            ['dati2' => '6191', 'nama' => 'MAKASSAR, KOTA', 'province_id' => '73'],
            ['dati2' => '6192', 'nama' => 'PARE PARE, KOTA', 'province_id' => '73'],
            ['dati2' => '6193', 'nama' => 'PALOPO, KOTA', 'province_id' => '73'],
            ['dati2' => '6202', 'nama' => 'MINAHASA, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6203', 'nama' => 'BOLAANG MONGONDOW, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6204', 'nama' => 'SANGIHE, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6205', 'nama' => 'KEPULAUAN TALAUD, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6206', 'nama' => 'MINAHASA SELATAN, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6207', 'nama' => 'MINAHASA UTARA, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6209', 'nama' => 'MINAHASA TENGGARA, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6210', 'nama' => 'BOLAANG MONGOUNDOW UTARA, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6211', 'nama' => 'KEPULAUAN SITARO, KABUPATEN', 'province_id' => '71'],
            ['dati2' => '6212', 'nama' => 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'province_id' => '71'],
            ['dati2' => '6213', 'nama' => 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'province_id' => '71'],
            ['dati2' => '6288', 'nama' => 'SULAWESI UTARA, KABUPATEN/KOTA LAINNYA', 'province_id' => '71'],
            ['dati2' => '6291', 'nama' => 'MENADO, KOTA', 'province_id' => '71'],
            ['dati2' => '6292', 'nama' => 'KOTAMOBAGU, KOTA', 'province_id' => '71'],
            ['dati2' => '6293', 'nama' => 'BITUNG, KOTA', 'province_id' => '71'],
            ['dati2' => '6294', 'nama' => 'KOTA TOMOHON', 'province_id' => '71'],
            ['dati2' => '6301', 'nama' => 'GORONTALO, KABUPATEN', 'province_id' => '75'],
            ['dati2' => '6302', 'nama' => 'BUALEMO, KABUPATEN', 'province_id' => '75'],
            ['dati2' => '6303', 'nama' => 'BONEBOLANGO, KABUPATEN', 'province_id' => '75'],
            ['dati2' => '6304', 'nama' => 'POHUWATO, KABUPATEN', 'province_id' => '75'],
            ['dati2' => '6305', 'nama' => 'GORONTALO UTARA, KABUPATEN', 'province_id' => '75'],
            ['dati2' => '6388', 'nama' => 'PROV GORONTALO, KABUPATEN/KOTA LAINNYA', 'province_id' => '75'],
            ['dati2' => '6391', 'nama' => 'GORONTALO, KOTA', 'province_id' => '75'],
            ['dati2' => '6401', 'nama' => 'POLEWALI MANDAR, KABUPATEN', 'province_id' => '76'],
            ['dati2' => '6402', 'nama' => 'MAJENE, KABUPATEN', 'province_id' => '76'],
            ['dati2' => '6403', 'nama' => 'MAMASA, KABUPATEN', 'province_id' => '76'],
            ['dati2' => '6404', 'nama' => 'MAMUJU UTARA, KABUPATEN', 'province_id' => '76'],
            ['dati2' => '6405', 'nama' => 'MAMUJU TENGAH, KABUPATENUPATEN', 'province_id' => '76'],
            ['dati2' => '6488', 'nama' => 'PROVSULAWESI BARAT, KABUPATEN/KOTA LAINNYA', 'province_id' => '76'],
            ['dati2' => '6491', 'nama' => 'MAMUJU, KOTA', 'province_id' => '76'],
            ['dati2' => '6901', 'nama' => 'BUTON, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6903', 'nama' => 'MUNA, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6904', 'nama' => 'KOLAKA, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6905', 'nama' => 'WAKATOBI, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6906', 'nama' => 'KONAWE, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6907', 'nama' => 'KONAWE SELATAN, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6908', 'nama' => 'BOMBANA, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6909', 'nama' => 'KOLAKA UTARA, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6910', 'nama' => 'BUTON UTARA, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6911', 'nama' => 'KONAWE UTARA, KABUPATEN', 'province_id' => '74'],
            ['dati2' => '6912', 'nama' => 'KOLAKA TIMUR, KABUPATENUPATEN', 'province_id' => '74'],
            ['dati2' => '6913', 'nama' => 'KONAWE KEPULAUAN, KABUPATENUPATEN', 'province_id' => '74'],
            ['dati2' => '6914', 'nama' => 'BUTON SELATAN  KABUPATENUPATEN', 'province_id' => '74'],
            ['dati2' => '6915', 'nama' => 'BUTON TENGAH  KABUPATENUPATEN', 'province_id' => '74'],
            ['dati2' => '6916', 'nama' => 'MUNA BARAT, KABUPATENUPATEN', 'province_id' => '74'],
            ['dati2' => '6988', 'nama' => 'PROVSULAWESI TENGGARA,KABUPATEN/KOTA LAINNYA', 'province_id' => '74'],
            ['dati2' => '6990', 'nama' => 'BAU BAU,KOTA', 'province_id' => '74'],
            ['dati2' => '6991', 'nama' => 'KENDARI, KOTA', 'province_id' => '74'],
            ['dati2' => '7101', 'nama' => 'LOMBOK BARAT, KABUPATEN', 'province_id' => '52'],
            ['dati2' => '7102', 'nama' => 'LOMBOK TENGAH, KABUPATEN', 'province_id' => '52'],
            ['dati2' => '7103', 'nama' => 'LOMBOK TIMUR, KABUPATEN', 'province_id' => '52'],
            ['dati2' => '7104', 'nama' => 'SUMBAWA, KABUPATEN', 'province_id' => '52'],
            ['dati2' => '7105', 'nama' => 'BIMA, KABUPATEN', 'province_id' => '52'],
            ['dati2' => '7106', 'nama' => 'DOMPU, KABUPATEN', 'province_id' => '52'],
            ['dati2' => '7107', 'nama' => 'SUMBAWA BARAT, KABUPATEN', 'province_id' => '52'],
            ['dati2' => '7108', 'nama' => 'KABUPATEN LOMBOK UTARA', 'province_id' => '52'],
            ['dati2' => '7188', 'nama' => 'PROV NTB, KABUPATEN/KOTA LAINNYA', 'province_id' => '52'],
            ['dati2' => '7191', 'nama' => 'MATARAM, KOTA', 'province_id' => '52'],
            ['dati2' => '7192', 'nama' => 'KOTA BIMA', 'province_id' => '52'],
            ['dati2' => '7201', 'nama' => 'BULELENG, KABUPATEN', 'province_id' => '51'],
            ['dati2' => '7202', 'nama' => 'JEMBRANA, KABUPATEN', 'province_id' => '51'],
            ['dati2' => '7203', 'nama' => 'TABANAN, KABUPATEN', 'province_id' => '51'],
            ['dati2' => '7204', 'nama' => 'BADUNG, KABUPATEN', 'province_id' => '51'],
            ['dati2' => '7205', 'nama' => 'GIANYAR, KABUPATEN', 'province_id' => '51'],
            ['dati2' => '7206', 'nama' => 'KLUNGKUNG, KABUPATEN', 'province_id' => '51'],
            ['dati2' => '7207', 'nama' => 'BANGLI, KABUPATEN', 'province_id' => '51'],
            ['dati2' => '7208', 'nama' => 'KARANGASEM, KABUPATEN', 'province_id' => '51'],
            ['dati2' => '7288', 'nama' => 'PROV BALI, KABUPATEN/KOTA LAINNYA', 'province_id' => '51'],
            ['dati2' => '7291', 'nama' => 'DENPASAR, KOTA', 'province_id' => '51'],
            ['dati2' => '7401', 'nama' => 'KUPANG, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7402', 'nama' => 'TIMOR TENGAH SELATAN, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7403', 'nama' => 'TIMOR TENGAH UTARA, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7404', 'nama' => 'BELU, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7405', 'nama' => 'ALOR, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7406', 'nama' => 'FLORES TIMUR, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7407', 'nama' => 'SIKKA, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7408', 'nama' => 'ENDE, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7409', 'nama' => 'NGADA, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7410', 'nama' => 'MANGGARAI, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7411', 'nama' => 'SUMBA TIMUR, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7412', 'nama' => 'SUMBA BARAT, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7413', 'nama' => 'LEMBATA, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7414', 'nama' => 'ROTE, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7415', 'nama' => 'MANGGARAI BARAT, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7416', 'nama' => 'SUMBA TENGAH, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7417', 'nama' => 'SUMBA BARAT DAYA, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7418', 'nama' => 'MANGGARAI TIMUR, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7419', 'nama' => 'NAGEKEO, KABUPATEN', 'province_id' => '53'],
            ['dati2' => '7420', 'nama' => 'KABUPATEN SABU RAIJUA', 'province_id' => '53'],
            ['dati2' => '7421', 'nama' => 'MALAKA, KABUPATENUPATEN', 'province_id' => '53'],
            ['dati2' => '7488', 'nama' => 'PROV NTT, KABUPATEN/KOTA LAINNYA', 'province_id' => '53'],
            ['dati2' => '7491', 'nama' => 'KUPANG, KOTA', 'province_id' => '53'],
            ['dati2' => '8101', 'nama' => 'MALUKU TENGAH, KABUPATEN', 'province_id' => '81'],
            ['dati2' => '8102', 'nama' => 'MALUKU TENGGARA, KABUPATEN', 'province_id' => '81'],
            ['dati2' => '8103', 'nama' => 'MALUKU TENGGARA BARAT, KABUPATEN', 'province_id' => '81'],
            ['dati2' => '8104', 'nama' => 'KABUPATEN BURU', 'province_id' => '81'],
            ['dati2' => '8105', 'nama' => 'SERAM BAGIAN BARAT, KOTA', 'province_id' => '81'],
            ['dati2' => '8106', 'nama' => 'SERAM BAGIAN TIMUR, KOTA', 'province_id' => '81'],
            ['dati2' => '8107', 'nama' => 'KEPULAUAN ARU, KOTA', 'province_id' => '81'],
            ['dati2' => '8108', 'nama' => 'KABUPATEN MALUKU BARAT DAYA', 'province_id' => '81'],
            ['dati2' => '8109', 'nama' => 'KABUPATEN BURU SELATAN', 'province_id' => '81'],
            ['dati2' => '8188', 'nama' => 'PROV MALUKU, KABUPATEN/KOTA LAINNYA', 'province_id' => '81'],
            ['dati2' => '8191', 'nama' => 'AMBON, KOTA', 'province_id' => '81'],
            ['dati2' => '8192', 'nama' => 'TUAL, KOTA', 'province_id' => '81'],
            ['dati2' => '8201', 'nama' => 'JAYAPURA, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8202', 'nama' => 'BIAK NUMFOR, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8210', 'nama' => 'YAPEN WAROPEN, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8211', 'nama' => 'MERAUKE, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8212', 'nama' => 'PANIAI, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8213', 'nama' => 'JAYAWIJAYA, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8214', 'nama' => 'NABIRE, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8215', 'nama' => 'MIMIKA, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8216', 'nama' => 'PUNCAK JAYA, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8217', 'nama' => 'SARMI, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8218', 'nama' => 'KEEROM, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8221', 'nama' => 'PEGUNUNGAN BINTANG, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8222', 'nama' => 'YAHUKIMO, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8223', 'nama' => 'TOLIKARA, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8224', 'nama' => 'WAROPEN, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8226', 'nama' => 'BOVEN DIGOEL, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8227', 'nama' => 'MAPPI, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8228', 'nama' => 'ASMAT, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8231', 'nama' => 'SUPIORI,KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8232', 'nama' => 'MAMBERAMO RAYA, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8233', 'nama' => 'DOGIYAI, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8234', 'nama' => 'LANNY JAYA, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8235', 'nama' => 'MAMBERAMO TENGAH, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8236', 'nama' => 'NDUGA TENGAH, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8237', 'nama' => 'YALIMO, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8238', 'nama' => 'PUNCAK, KABUPATEN', 'province_id' => '91'],
            ['dati2' => '8239', 'nama' => 'KABUPATEN INTAN JAYA', 'province_id' => '91'],
            ['dati2' => '8240', 'nama' => 'KABUPATEN DEIYAI', 'province_id' => '91'],
            ['dati2' => '8288', 'nama' => 'PROV PAPUA, KABUPATEN/KOTA LAINNYA', 'province_id' => '91'],
            ['dati2' => '8291', 'nama' => 'JAYAPURA, KOTA', 'province_id' => '91'],
            ['dati2' => '8302', 'nama' => 'HALMAHERA TENGAH, KABUPATEN', 'province_id' => '82'],
            ['dati2' => '8303', 'nama' => 'HALMAHERA UTARA, KABUPATEN', 'province_id' => '82'],
            ['dati2' => '8304', 'nama' => 'HALMAHERA TIMUR, KABUPATEN', 'province_id' => '82'],
            ['dati2' => '8305', 'nama' => 'HALMAHERA BARAT, KABUPATEN', 'province_id' => '82'],
            ['dati2' => '8306', 'nama' => 'HALMAHERA SELATAN, KABUPATEN', 'province_id' => '82'],
            ['dati2' => '8307', 'nama' => 'KEPULAUAN SULA, KABUPATEN', 'province_id' => '82'],
            ['dati2' => '8308', 'nama' => 'KABUPATEN PULAU MOROTAI', 'province_id' => '82'],
            ['dati2' => '8309', 'nama' => 'PULAU TALIABU, KABUPATENUPATEN', 'province_id' => '82'],
            ['dati2' => '8388', 'nama' => 'PROV MALUKU UTARA, KABUPATEN/KOTA LAINNYA', 'province_id' => '82'],
            ['dati2' => '8390', 'nama' => 'TERNATE, KOTA', 'province_id' => '82'],
            ['dati2' => '8391', 'nama' => 'TIDORE KEPULAUAN, KOTA', 'province_id' => '82'],
            ['dati2' => '8401', 'nama' => 'SORONG, KABUPATEN', 'province_id' => '92'],
            ['dati2' => '8402', 'nama' => 'FAK FAK, KABUPATEN', 'province_id' => '92'],
            ['dati2' => '8403', 'nama' => 'MANOKWARI, KABUPATEN', 'province_id' => '92'],
            ['dati2' => '8404', 'nama' => 'SORONG SELATAN, KABUPATEN', 'province_id' => '92'],
            ['dati2' => '8405', 'nama' => 'RAJA AMPAT, KABUPATEN', 'province_id' => '92'],
            ['dati2' => '8406', 'nama' => 'KAIMANA, KABUPATEN', 'province_id' => '92'],
            ['dati2' => '8407', 'nama' => 'TELUK BINTUNI, KABUPATEN', 'province_id' => '92'],
            ['dati2' => '8408', 'nama' => 'TELUK WONDAMA, KABUPATEN', 'province_id' => '92'],
            ['dati2' => '8409', 'nama' => 'KABUPATEN TEMBRAUW', 'province_id' => '92'],
            ['dati2' => '8410', 'nama' => 'KABUPATEN MAYBRAT', 'province_id' => '92'],
            ['dati2' => '8411', 'nama' => 'PEGUNUNGAN ARFAK, KABUPATENUPATEN', 'province_id' => '92'],
            ['dati2' => '8412', 'nama' => 'MANOKWARI SELATAN  KABUPATENUPATEN', 'province_id' => '92'],
            ['dati2' => '8488', 'nama' => 'PROVIRIAN JAYA BARAT, KABUPATEN/KOTA LAINNYA', 'province_id' => '92'],
            ['dati2' => '8491', 'nama' => 'SORONG, KOTA', 'province_id' => '92'],
            ['dati2' => '9999', 'nama' => 'DI  LUAR  INDONESIA', 'province_id' => '00'],
        ];

        DB::table('city')->insert($data);
    }
}
