<?php

return [
    'categories' => [
        'Manajemen Role' => [
            'icon' => 'security',
            'route' => 'roles.index',
            'permission' => 'roles.view',
            'roles' => ['admin'],
        ],
        'Manajemen User' => [
            'icon' => 'person',
            'route' => 'users.index',
            'permission' => 'users.view',
            'roles' => ['admin'],
        ],
        'Dashboard' => [
            'icon' => 'dashboard',
            'route' => 'dashboard',
            'permission' => 'dashboard.view',
            'roles' => ['admin'],
        ],
    ],
    'master_data' => [
        'Manajemen Cabang' => [
            'icon' => 'account_tree',
            'route' => 'branches.index',
            'permission' => 'branches.view',
            'roles' => ['admin'],
        ],
        'Data Kota/Kabupaten' => [
            'icon' => 'location_city',
            'route' => 'cities.index',
            'permission' => 'cities.view',
            'roles' => ['admin'],
        ],
        'Manajemen Perusahaan' => [
            'icon' => 'domain',
            'route' => 'companies.index',
            'permission' => 'companies.view',
            'roles' => ['admin'],
        ],
        'Data Kecamatan' => [
            'icon' => 'share_location',
            'route' => 'districts.index',
            'permission' => 'districts.view',
            'roles' => ['admin'],
        ],
        'Marketing Master' => [
            'icon' => 'recent_actors',
            'route' => 'marketing-masters.index',
            'permission' => 'marketing-masters.view',
            'roles' => ['admin'],
        ],
        'Data Provinsi' => [
            'icon' => 'public',
            'route' => 'provinces.index',
            'permission' => 'provinces.view',
            'roles' => ['admin'],
        ],
        'Data Kelurahan' => [
            'icon' => 'maps_home_work',
            'route' => 'subdistricts.index',
            'permission' => 'subdistricts.view',
            'roles' => ['admin'],
        ],
    ],
    'master_produk' => [
        'Produk Simpanan Berjangka' => [
            'icon' => 'inventory_2',
            'route' => 'deposit-products.index',
            'permission' => 'deposit-products.view',
            'roles' => ['admin'],
        ],
        'Produk Pinjaman' => [
            'icon' => 'payments',
            'route' => 'loan-products.index',
            'permission' => 'loan-products.view',
            'roles' => ['admin'],
        ],
        'Produk Simpanan' => [
            'icon' => 'savings',
            'route' => 'saving-products.index',
            'permission' => 'saving-products.view',
            'roles' => ['admin'],
        ],
    ],
    'system' => [
        'Daftar Persetujuan' => [
            'icon' => 'fact_check',
            'route' => 'approvals.inbox',
            'permission' => 'view.approvals',
            'roles' => ['admin'],
        ],
        'Audit Log' => [
            'icon' => 'history',
            'route' => 'audit.logs',
            'permission' => 'logs.view',
            'roles' => ['admin'],
        ],
        'Tanggal Operasional' => [
            'icon' => 'event_repeat',
            'route' => 'system.business-date',
            'permission' => 'system.business-date',
            'roles' => ['admin'],
        ],
        'Manajemen Menu' => [
            'icon' => 'menu',
            'route' => 'menus.index',
            'permission' => 'menus.view',
            'roles' => ['admin'],
        ],
        'Pusat Laporan' => [
            'icon' => 'assessment',
            'route' => 'reports.index',
            'permission' => 'reports.index',
            'roles' => ['admin'],
        ],
        'Pengaturan Persetujuan' => [
            'icon' => 'settings_suggest',
            'route' => 'approvals.settings',
            'permission' => 'manage.approvals',
            'roles' => ['admin'],
        ],
    ],
    'saving' => [
        'Buka Rekening Baru' => [
            'icon' => 'add_card',
            'route' => 'savings.create',
            'permission' => 'savings.create',
            'roles' => ['admin'],
        ],
        'Inquiry Simpanan' => [
            'icon' => 'person_search',
            'route' => 'savings.inquiry',
            'permission' => 'savings.inquiry',
            'roles' => ['admin'],
        ],
        'Setoran Simpanan' => [
            'icon' => 'savings',
            'route' => 'savings.deposit',
            'permission' => 'savings.deposit',
            'roles' => ['admin'],
        ],
        'Penarikan Simpanan' => [
            'icon' => 'money_off',
            'route' => 'savings.withdrawal',
            'permission' => 'savings.withdrawal',
            'roles' => ['admin'],
        ],
        'Transfer Antar Rekening' => [
            'icon' => 'sync_alt',
            'route' => 'savings.transfer',
            'permission' => 'savings.transfer',
            'roles' => ['admin'],
        ],
        'Blokir Saldo' => [
            'icon' => 'lock',
            'route' => 'savings.block',
            'permission' => 'savings.block',
            'roles' => ['admin'],
        ],
        'Buka Blokir Saldo' => [
            'icon' => 'lock_open',
            'route' => 'savings.unblock',
            'permission' => 'savings.unblock',
            'roles' => ['admin'],
        ],
        'Reversal Transaksi' => [
            'icon' => 'settings_backup_restore',
            'route' => 'savings.reversal',
            'permission' => 'savings.reversal',
            'roles' => ['admin'],
        ],
        'Cetak Buku Tabungan' => [
            'icon' => 'menu_book',
            'route' => 'savings.print-book',
            'permission' => 'savings.print-book',
            'roles' => ['admin'],
        ],
        'Cetak Slip Transaksi' => [
            'icon' => 'receipt_long',
            'route' => 'savings.print-slip',
            'permission' => 'savings.print-slip',
            'roles' => ['admin'],
        ],
        'Penutupan Rekening' => [
            'icon' => 'cancel',
            'route' => 'savings.close',
            'permission' => 'savings.close',
            'roles' => ['admin'],
        ],
        'Status Dormant' => [
            'icon' => 'bedtime',
            'route' => 'savings.dormant',
            'permission' => 'savings.dormant',
            'roles' => ['admin'],
        ],
        'Aktivasi Rekening' => [
            'icon' => 'published_with_changes',
            'route' => 'savings.reactivate',
            'permission' => 'savings.reactivate',
            'roles' => ['admin'],
        ],
        'Statement' => [
            'icon' => 'link',
            'route' => 'savings.statement',
            'permission' => 'savings.statement',
            'roles' => ['admin'],
        ],
        'Distribusi Dana Simpanan' => [
            'icon' => 'account_balance_wallet',
            'route' => 'savings.distribution',
            'permission' => 'savings.distribution',
            'roles' => ['admin'],
        ],
    ],
    'deposit' => [
        'Penempatan Simpanan Berjangka Baru' => [
            'icon' => 'add_task',
            'route' => 'deposits.placement',
            'permission' => 'deposits.placement',
            'roles' => ['admin'],
        ],
        'Inquiry Simpanan Berjangka' => [
            'icon' => 'account_balance_wallet',
            'route' => 'deposits.inquiry',
            'permission' => 'deposits.inquiry',
            'roles' => ['admin'],
        ],
        'Manajemen Bilyet' => [
            'icon' => 'inventory',
            'route' => 'deposit-bilyets.index',
            'permission' => 'deposit-bilyets.view',
            'roles' => ['admin'],
        ],
        'Perubahan Simpanan Berjangka' => [
            'icon' => 'edit_note',
            'route' => 'deposits.modification',
            'permission' => 'deposits.modification',
            'roles' => ['admin'],
        ],
        'Cetak Bilyet Simpanan Berjangka' => [
            'icon' => 'print',
            'route' => 'deposits.print-bilyet',
            'permission' => 'deposits.print-bilyet',
            'roles' => ['admin'],
        ],
        'Simulasi Simpanan Berjangka' => [
            'icon' => 'calculate',
            'route' => 'deposits.simulation',
            'permission' => 'deposits.simulation',
            'roles' => ['admin'],
        ],
        'Pencairan Simpanan Berjangka' => [
            'icon' => 'money_off',
            'route' => 'deposits.withdrawal',
            'permission' => 'deposits.withdrawal',
            'roles' => ['admin'],
        ],
        'Pembayaran Bunga Simpanan Berjangka' => [
            'icon' => 'payments',
            'route' => 'deposits.interest-payment',
            'permission' => 'deposits.interest-payment',
            'roles' => ['admin'],
        ],
    ],
    'loan' => [
        'Pendaftaran Pinjaman' => [
            'icon' => 'post_add',
            'route' => 'loans.origination',
            'permission' => 'loans.origination',
            'roles' => ['admin'],
        ],
        'Inquiry Pinjaman' => [
            'icon' => 'credit_score',
            'route' => 'loans.inquiry',
            'permission' => 'loans.inquiry',
            'roles' => ['admin'],
        ],
        'Pencairan Dana Pinjaman' => [
            'icon' => 'request_quote',
            'route' => 'loans.disbursement',
            'permission' => 'loans.disbursement',
            'roles' => ['admin'],
        ],
        'Pembayaran Angsuran' => [
            'icon' => 'payments',
            'route' => 'loans.repayment',
            'permission' => 'loans.repayment',
            'roles' => ['admin'],
        ],
        'Simulasi Pinjaman' => [
            'icon' => 'calculate',
            'route' => 'loans.simulation',
            'permission' => 'loans.simulation',
            'roles' => ['admin'],
        ],
        'Reversal Distribusi Pinjaman' => [
            'icon' => 'settings_backup_restore',
            'route' => 'loans.reversal',
            'permission' => 'loans.reversal',
            'roles' => ['admin'],
        ],
        'Dokumen Pinjaman' => [
            'icon' => 'folder_open',
            'route' => 'loans.documents',
            'permission' => 'loans.documents',
            'roles' => ['admin'],
        ],
        'Klaim Asuransi Pinjaman' => [
            'icon' => 'link',
            'route' => 'loans.insurance-claims',
            'permission' => 'loans.insurance-claims',
            'roles' => ['admin'],
        ],
        'Pelunasan Pinjaman' => [
            'icon' => 'task_alt',
            'route' => 'loans.settlement',
            'permission' => 'loans.settlement',
            'roles' => ['admin'],
        ],
        'Perubahan Pengajuan Pinjaman' => [
            'icon' => 'edit_note',
            'route' => 'loans.edit',
            'permission' => 'loans.edit',
            'roles' => ['admin'],
        ],
    ],
    'cif' => [
        'Registrasi CIF' => [
            'icon' => 'person_add',
            'route' => 'cifs.create',
            'permission' => 'cifs.create',
            'roles' => ['admin'],
        ],
        'Inquiry CIF' => [
            'icon' => 'visibility',
            'route' => 'cifs.inquiry',
            'permission' => 'cifs.inquiry',
            'roles' => ['admin'],
        ],
        'Ubah Data CIF' => [
            'icon' => 'manage_accounts',
            'route' => 'cifs.update',
            'permission' => 'cifs.update',
            'roles' => ['admin'],
        ],
        'Nonaktifkan CIF' => [
            'icon' => 'person_off',
            'route' => 'cifs.inactive',
            'permission' => 'cifs.inactive',
            'roles' => ['admin'],
        ],
        'Blokir CIF' => [
            'icon' => 'gpp_bad',
            'route' => 'cifs.block',
            'permission' => 'cifs.block',
            'roles' => ['admin'],
        ],
        'Reaktivasi CIF' => [
            'icon' => 'how_to_reg',
            'route' => 'cifs.reactivate',
            'permission' => 'cifs.reactivate',
            'roles' => ['admin'],
        ],
        'Mutasi Cabang CIF' => [
            'icon' => 'transfer_within_a_station',
            'route' => 'cifs.mutation',
            'permission' => 'cifs.mutation',
            'roles' => ['admin'],
        ],
        'Akses Mobile' => [
            'icon' => 'smartphone',
            'route' => 'mobile-access.index',
            'permission' => 'mobile-access.index',
            'roles' => ['admin'],
        ],
    ],
    'akuntansi' => [
        'Chart of Accounts' => [
            'icon' => 'account_tree',
            'route' => 'coa.index',
            'permission' => 'coa.view',
            'roles' => ['admin'],
        ],
        'Jurnal Umum' => [
            'icon' => 'menu_book',
            'route' => 'journals.index',
            'permission' => 'journals.view',
            'roles' => ['admin'],
        ],
        'Buku Besar' => [
            'icon' => 'import_contacts',
            'route' => 'ledger.index',
            'permission' => 'ledger.view',
            'roles' => ['admin'],
        ],
        'Pengaturan Pajak' => [
            'icon' => 'percent',
            'route' => 'tax-settings.index',
            'permission' => 'tax-settings.view',
            'roles' => ['admin'],
        ],
        'Neraca Saldo' => [
            'icon' => 'balance',
            'route' => 'trial-balance.index',
            'permission' => 'trial-balance.view',
            'roles' => ['admin'],
        ],
    ],
    'produk_layanan' => [
    ],
    'aset_sewa' => [
        'Jasa Sewa' => [
            'icon' => 'receipt_long',
            'route' => 'asset-rentals.index',
            'permission' => 'asset-rentals.index',
            'roles' => ['admin'],
        ],
        'Daftar Inventaris' => [
            'icon' => 'inventory_2',
            'route' => 'assets.inquiry',
            'permission' => 'assets.inquiry',
            'roles' => ['admin'],
        ],
        'Kategori Aset' => [
            'icon' => 'link',
            'route' => 'assets.categories',
            'permission' => 'assets.categories',
            'roles' => ['admin'],
        ],
        'Tambah Aset Baru' => [
            'icon' => 'add_circle',
            'route' => 'assets.create',
            'permission' => 'assets.create',
            'roles' => ['admin'],
        ],
        'Penyusutan Aset' => [
            'icon' => 'trending_down',
            'route' => 'assets.depreciation',
            'permission' => 'assets.depreciation',
            'roles' => ['admin'],
        ],
        'Master Rekanan' => [
            'icon' => 'handshake',
            'route' => 'rekanan.index',
            'permission' => 'rekanan.index',
            'roles' => ['admin'],
        ],
        'Pembayaran Sewa Aset Masal' => [
            'icon' => 'upload_file',
            'route' => 'asset-rentals.payment-import',
            'permission' => 'asset-rentals.payment-import',
            'roles' => ['admin'],
        ],
        'Perubahan Inventaris' => [
            'icon' => 'edit',
            'route' => 'assets.update',
            'permission' => 'assets.update',
            'roles' => ['admin'],
        ],
    ],
    'asuransi' => [
        'Produk Asuransi' => [
            'icon' => 'add_task',
            'route' => 'insurance-products.index',
            'permission' => 'insurance-products.index',
            'roles' => ['admin'],
        ],
        'Provider Asuransi' => [
            'icon' => 'domain_add',
            'route' => 'insurance-providers.index',
            'permission' => 'insurance-providers.index',
            'roles' => ['admin'],
        ],
    ],
    'manajemen_shu' => [
        'Master SHU' => [
            'icon' => 'settings',
            'route' => 'shu.master.index',
            'permission' => 'shu.master.index',
            'roles' => ['admin'],
        ],
        'Distribusi SHU' => [
            'icon' => 'payments',
            'route' => 'shu.transactions.index',
            'permission' => 'shu.transactions.index',
            'roles' => ['admin'],
        ],
    ],
    'extra_permissions' => [
        'dashboard.view' => ['admin'],
    ],
];
